"""add_file_type_to_banner

Revision ID: 111564e11f35
Revises: 291b19ab1f42
Create Date: 2025-02-18 19:35:12.923951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111564e11f35'
down_revision: Union[str, None] = '291b19ab1f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('file_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'file_type')
    # ### end Alembic commands ###
