"""Add file_type to Product

Revision ID: 73296efd80f6
Revises: dcb44c7e2e43
Create Date: 2025-03-05 15:46:36.983856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73296efd80f6'
down_revision: Union[str, None] = 'dcb44c7e2e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
