"""add_status_to_orders

Revision ID: 84670c4f7c18
Revises: fa3624e1d703
Create Date: 2025-03-19 01:33:13.383045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84670c4f7c18'
down_revision: Union[str, None] = 'fa3624e1d703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Создаем тип order_status, если он еще не существует
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
                CREATE TYPE order_status AS ENUM ('PROCESSING', 'READY_FOR_PICKUP', 'COMPLETED', 'CANCELLED');
            END IF;
        END $$;
    """)

    # Изменяем тип столбца status на order_status
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PROCESSING', 'READY_FOR_PICKUP', 'COMPLETED', 'CANCELLED', name='order_status'),
               postgresql_using='status::order_status',  # Преобразуем существующие данные
               existing_nullable=True)

    # Удаляем старый внешний ключ
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')

    # Создаем новый внешний ключ
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])

    # Делаем subcategory_id обязательным
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Возвращаем subcategory_id к nullable=True
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # Удаляем новый внешний ключ
    op.drop_constraint(None, 'orders', type_='foreignkey')

    # Восстанавливаем старый внешний ключ
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['user_id'])

    # Возвращаем тип столбца status к VARCHAR
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PROCESSING', 'READY_FOR_PICKUP', 'COMPLETED', 'CANCELLED', name='order_status'),
               type_=sa.VARCHAR(length=50),
               postgresql_using='status::varchar',  # Преобразуем данные обратно
               existing_nullable=True)

    # Удаляем тип order_status, если он существует
    op.execute("DROP TYPE IF EXISTS order_status")
    # ### end Alembic commands ###