"""data

Revision ID: c9ceb1b5d3a8
Revises: 7eae9d0e9f4e
Create Date: 2025-03-06 01:01:18.726529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ceb1b5d3a8'
down_revision: Union[str, None] = '7eae9d0e9f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
