"""Add file_type to Product

Revision ID: dcb44c7e2e43
Revises: 8b6d4677eaa8
Create Date: 2025-03-05 15:13:28.323056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb44c7e2e43'
down_revision: Union[str, None] = '8b6d4677eaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('file_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'file_type')
    # ### end Alembic commands ###
