"""add product_images table

Revision ID: fa3624e1d703
Revises: c9ceb1b5d3a8
Create Date: 2025-03-16 00:36:41.952920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa3624e1d703'
down_revision: Union[str, None] = 'c9ceb1b5d3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart_items', 'users', ['user_id'], ['id'])
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    # ### end Alembic commands ###
